[linux_vms]
agent1 ansible_host=agent1
agent2 ansible_host=agent2

[linux_vms:vars]
ansible_user=root
ansible_connection=ssh
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
